base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path("", views.home, name="home"),
    path("sign-in/", views.signIn, name="sign-in"),
    path("sign-up/", views.signUp, name="sign-up"),
    path("logout/", views.logoutUser, name="logout"),
    path("blog/<int:pk>/", views.showBlog, name="blog-details"),
    path("blog/create/", views.createBlog, name="create-blog"),
    path("blog/<int:pk>/like/", views.likeBlog, name="like-blog"),
    path("blog/<int:pk>/comment/", views.commentBlog, name="comment-blog"),
    path("blog/delete/<int:pk>", views.deleteBlog, name="delete-blog"),



    path('contact/', views.contact_us_view, name='contact_us'),
    path('about/', views.about_us_view, name='about_us'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/header.html
{% load static %}
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <button
                class="navbar-toggler mb-3"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul
                    class="navbar-nav d-flex align-items-lg-center justify-content-lg-between w-100 px-lg-5 gap-lg-5 gap-3"
                >
                    <div class="d-flex flex-lg-row flex-column nav-left">
                        <li class="nav-item">
                            <a
                                class="nav-link {% if request.path == '/' %}active{% endif %}"
                                aria-current="page"
                                href="{% url "base:home" %}"
                                >Home</a
                            >
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/about/'%}active{% endif %}" href="{% url "base:about_us" %}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/contact/'%}active{% endif %}" href="{% url "base:contact_us" %}">Contact</a>
                        </li>
                    </div>
                    {% if request.user.is_authenticated %}
                    <div class="btn-group d-flex flex-lg-row flex-column gap-3">
                        <button type="button" class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                            {{request.user.name}}
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url "base:logout" %}">logut</a></li>
                        </ul>
                    </div>
                    {% else%}
                    <div class="d-flex flex-lg-row flex-column gap-3">
                        <li class="nav-item">
                            <a class="btn btn-outline-danger" href="{% url 'base:sign-in' %}"
                                >Sign in</a
                            >
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-success" href="{% url 'base:sign-up' %}"
                                >Sign up</a
                            >
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

<script src="{% static "js/header.js" %}"></script>

templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            type="text/css"
            href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css"
        />
        {% block style %}{% endblock %}
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        {% include "header.html" %}
        <main class="container">{% block content %}{% endblock %}</main>
    </body>

    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"
    ></script>
    <script
        type="text/javascript"
        src="https://cdn.jsdelivr.net/npm/toastify-js"
    ></script>

    <script
        src="https://kit.fontawesome.com/55a3fd6aba.js"
        crossorigin="anonymous"
    ></script>
    {% block script %}{% endblock  %}
</html>