base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path("", views.home, name="home"),
    path("sign-in/", views.signIn, name="sign-in"),
    path("sign-up/", views.signUp, name="sign-up"),
    path("logout/", views.logoutUser, name="logout"),
    path("blog/<int:pk>/", views.showBlog, name="blog-details"),
    path("blog/create/", views.createBlog, name="create-blog"),
    path("blog/<int:pk>/like/", views.likeBlog, name="like-blog"),
    path("blog/<int:pk>/comment/", views.commentBlog, name="comment-blog"),
    path("blog/delete/<int:pk>", views.deleteBlog, name="delete-blog"),



    path('contact/', views.contact_us_view, name='contact_us'),
    path('about/', views.about_us_view, name='about_us'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    name = models.CharField(max_length=250, null=True)
    email = models.EmailField(unique=True, null=True)
    avatar = models.ImageField(null=True, default='defaults/defaultAvatar.svg')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ["username"]


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey('Blog', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ['-created_at']


class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    category = models.ManyToManyField(Category, related_name='blogs')
    image = models.ImageField(
        null=True, default='defaults/defaultBlogImage.jpg')
    content = models.TextField()
    likes_count = models.PositiveIntegerField(default=0)
    liked_by = models.ManyToManyField(
        User, related_name='liked_posts', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class ContactPage(models.Model):
    email = models.EmailField()
    location = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=20)

    def __str__(self):
        return "Contact Us"


class AboutPage(models.Model):
    company_name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return "About Us"

base/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User, Blog
from django import forms


class MyUserCreatingForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["name", "username", 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(MyUserCreatingForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control pt-4 pb-2'
        self.fields['username'].widget.attrs['class'] = 'form-control pt-4 pb-2'
        self.fields['email'].widget.attrs['class'] = 'form-control pt-4 pb-2'
        self.fields['password1'].widget.attrs['class'] = 'form-control pt-4 pb-2'
        self.fields['password2'].widget.attrs['class'] = 'form-control pt-4 pb-2'

        self.fields['name'].widget.attrs['placeholder'] = 'Name'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Password'

base/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.contrib.auth import authenticate, login, logout
from .models import User, Blog, Category, Comment, ContactPage, AboutPage
from .forms import MyUserCreatingForm
from django.contrib.auth.decorators import login_required
import json

# Create your views here.


def home(request):
    filterCategory = request.GET.get('category')
    if filterCategory == "all" or filterCategory is None:
        blogs = Blog.objects.all()
    else:
        blogs = Blog.objects.filter(category__name=filterCategory)

    categories = Category.objects.all()
    categoriesContent = {}

    for blog in blogs:
        blog.content = blog.content[:200] + '...'

    for category in categories:
        categoriesContent[category.name] = category.blogs.all().count()

    context = {
        'blogs': blogs,
        'categoriesContent': categoriesContent,
    }
    return render(request, 'base/home.html', context=context)


@login_required(login_url='base:sign-in')
def createBlog(request):
    categories = Category.objects.all()

    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        categories = request.POST.getlist('category[]')
        image = request.FILES.get('banner')
        additional_categories = request.POST.get(
            'additioanlCategories')
        additional_categories = additional_categories.split(',')

        for add_category in additional_categories:
            if add_category != '':
                categories.append(add_category)

        if len(categories) == 0:
            categories = Category.objects.all()
            context = {'categories': categories,
                       'error': 'Please select a category'}
            return render(request, 'base/create-blog.html', context=context)

        if image is None:
            blog = Blog.objects.create(
                author=request.user,
                title=title,
                content=content,
            )
        else:
            blog = Blog.objects.create(
                author=request.user,
                title=title,
                content=content,
                image=image
            )

        for category in categories:
            category = Category.objects.get_or_create(name=category)[0]
            blog.category.add(category)

        return redirect('base:home')

    return render(request, 'base/create-blog.html', {'categories': categories})


@login_required(login_url='base:sign-in')
def deleteBlog(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    blog.delete()
    return HttpResponse(status=204, content_type='application/json',
                        data=json.dumps({'message': 'success'}))


def signIn(request):
    if request.user.is_authenticated:
        return redirect('base:home')

    if request.method == 'POST':
        email = request.POST['email'].lower()
        password = request.POST['password']
        try:
            user = User.objects.get(email=email)
        except:
            context = {"error": "User does not exist"}
            return render(request, 'base/sign-in.html', context=context)

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('base:home')
        else:
            context = {"error": "Invalid credentials"}
            return render(request, 'base/sign-in.html', context=context)

    return render(request, 'base/sign-in.html')


def signUp(request):
    if request.user.is_authenticated:
        return redirect('base:home')

    form = MyUserCreatingForm()

    if request.method == 'POST':
        form = MyUserCreatingForm(request.POST)
        if form.is_valid():
            form.save()
            login(request, form.instance)
            return redirect('base:home')
        else:
            context = {"form": form}
            return render(request, 'base/sign-up.html', context=context)

    return render(request, 'base/sign-up.html', {'form': form})


def logoutUser(request):
    logout(request)
    return redirect('base:home')


def showBlog(request, pk):
    blog = Blog.objects.get(pk=pk)
    comments = blog.comment_set.all()
    is_liked = blog.liked_by.filter(id=request.user.id).exists()
    like_count = blog.likes_count
    context = {'blog': blog, 'comments': comments,
               'is_liked': is_liked, 'like_count': like_count}
    return render(request, 'base/blog.html', context=context)


def commentBlog(request, pk):
    if not request.user.is_authenticated:
        return redirect('base:sign-in')

    if request.method == 'POST':
        message = request.POST.get('comment')
        blog = Blog.objects.get(pk=pk)
        comment = Comment.objects.create(
            author=request.user,
            blog=blog,
            content=message
        )
        blog.comment_set.add(comment)

    return redirect('base:blog-details', pk=pk)


def likeBlog(request, pk):
    blog = Blog.objects.get(pk=pk)
    if not request.user.is_authenticated:
        blog.likes_count += 1
        blog.save()
        return redirect('base:blog-details', pk=pk)

    if request.user in blog.liked_by.all():
        blog.liked_by.remove(request.user)
        blog.likes_count -= 1
    else:
        print('liked')
        blog.liked_by.add(request.user)
        blog.likes_count += 1

    blog.save()
    return redirect('base:blog-details', pk=pk)


def contact_us_view(request):
    page = ContactPage.objects.first()
    return render(request, 'base/contact.html', {'page': page, 'email': page.email})


def about_us_view(request):
    page = AboutPage.objects.first()
    return render(request, 'base/about.html', {'page': page})

base/templates/base/about.html
{% extends "layout.html" %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static "css/about.css" %}">
{% endblock  %}

{% block title %}
    About Us
{% endblock  %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-10  text-center">
            <h1>{{ page.company_name }}</h1>
            <p>{{ page.description }}</p>
        </div>
        
        <a href="{% url "base:contact_us" %}" class="btn btn-outline-warning border-2 w-75">Contact Us</a>
    </div>
{% endblock  %}

base/templates/base/blog.html
{% extends "layout.html" %}
{% block title %}Blog{% endblock  %}

{% block content %}
<section>
    <h1 class="text-center my-5">{{blog.title}}</h1>
    <p class="text-left">created by <span class="fw-bold">{{blog.author.name}}</span> at <span class="fw-bold">{{blog.created_at}}</span></p>
    <div class="d-flex justify-content-center">
        <div class="w-100">
            <img
                src="{{blog.image.url}}"
                class="card-img-top"
                alt="{{blog.title}}"
                class="img-fluid"
            />
            <div class="mt-5">
                <p class="text">{{blog.content}}</p>
            </div>
        </div>
    </div>
    <div>

    <div class="mt-3">
        <a class="btn btn-outline-success mb-2 {% if is_liked %}active{% endif %}" href="{% url "base:like-blog" blog.id %}">
            <i class="fas fa-thumbs-up"></i> Like
        </a>
        {% if like_count == 0 %}
            <p class="fw-bold">Nobody liked</p>
        {% elif like_count == 1 %}
            <p class="fw-bold">{{like_count}} person liked</p>
        {% else %}
            <p class="fw-bold">{{like_count}} people liked</p>
        {% endif %}
    </div>

</section>

<section>
    <h2 class="text-center my-5">Comments</h2>
    <div class="d-flex justify-content-center">
        <div class="w-100">
            <form action="{% url 'base:comment-blog' blog.id %}" method="POST">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    <textarea class="form-control" placeholder="Leave a comment here" id="comment" style="height: 100px" name="comment"></textarea>
                    <label for="comment">Write your comment</label>
                </div>
                <input type="submit" value="Send" class="btn btn-outline-primary w-100" />
            </form>
            
            <div class="mt-5 p-3" style="max-height: 500px; overflow: auto">
                <ul class="list-unstyled">
                    {% for comment in comments %}
                    <li class="mb-4 bg-warning p-2 rounded-4">
                        <div class="d-flex justify-content-between fw-bold">
                            <p>@{{comment.author.username}} ({{comment.author.name}})</p>
                            <p>{{comment.created_at}}</p>
                        </div>
                        <p class="fs-6">
                            {{comment.content}}
                        </p>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</section>
{% endblock  %}

base/templates/base/contact.html
{% extends "layout.html" %} 
{% load static %} 
{% block style %} 
<link rel="stylesheet" href="{% static "css/contact.css" %}"> {% endblock %} 
{% block title %}Contact Us{% endblock %} 

{% block content %}


<div class="row gap-md-0 gap-5">
    <!-- Contact Form Section -->
    <div class="col-md-6 contact-form">
        <h2>Contact Us</h2>
        <form id="contactForm">
            <div class="form-group mb-3">
                <label for="subject" class="mb-2">Subject</label>
                <input
                    type="text"
                    class="form-control"
                    id="subject"
                    name="subject"
                    required
                />
            </div>
            <div class="form-group mb-3">
                <label for="message" class="mb-2">Message</label>
                <textarea
                    class="form-control"
                    id="message"
                    name="message"
                    rows="5"
                    required
                ></textarea>
            </div>
            <button type="submit" class="btn btn-primary w-100">
                Send Message
            </button>
        </form>
    </div>
    <!-- Contact Information Section -->
    <div class="col-md-6 contact-info">
        <h2>Contact Information</h2>
        <div class="info-item mb-3">
            <p><strong>Email:</strong> {{ page.email }}</p>
        </div>
        <div class="info-item mb-3">
            <p><strong>Location:</strong> {{ page.location }}</p>
        </div>
        <div class="info-item mb-3">
            <p><strong>Phone Number:</strong> {{ page.phone_number }}</p>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
    <script>
        const receiverEmail = "{{ email|escapejs }}";
    </script>
    <script src="{% static "js/contact.js" %}"></script>
{% endblock  %}

base/templates/base/create-blog.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
    Create Blog
{% endblock  %}
{% block content %}
    <h1 class="text-center my-5">Create Blog</h1>
    <form action="" method="POST" enctype="multipart/form-data" class="mb-5">
        {% csrf_token %}
        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="title" name="title" placeholder="Title" required>
            <label for="title">Title For Blog</label>
        </div>
        <div class="form-floating mb-3">
            <textarea class="form-control" placeholder="Write content here" id="content" name="content" style="height: 300px" required></textarea>
            <label for="content">Write content here</label>
        </div>

        {% if categories %}
            <div class="mb-3">
                {% for category in categories %}
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" id="category-{{category}}" value="{{category}}" name="category[]">
                        <label class="form-check-label" for="category-{{category}}">{{category}}</label>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        <div class="form-floating mb-3">
            <input type="text" class="form-control" id="additioanlCategories" name="additioanlCategories" placeholder="If your category is not presented, write by seperating with comma">
            <label for="additioanlCategories">Additional Categories (seperate with comma)</label>
        </div>

        <div class="input-group mb-3">
            <input type="file" class="form-control" id="banner" name="banner" accept="image/*">
            <label class="input-group-text" for="banner">Upload Image For Banner </label>
        </div>

        <input type="submit" class="btn btn-outline-warning border-2 w-100" value="Create" >
    </form>
{% endblock  %}

{% block script %}
    <script>
        const error = "{{ error|escapejs }}";
        const avatarURL = "{% static 'img/exclamation-mark.png' %}"
    </script>
    <script src="{% static "js/createBlog.js" %}"></script>
{% endblock  %}

base/templates/base/home.html
{% extends "layout.html" %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static "css/home.css" %}">
{% endblock  %}
{% block title %}Home{% endblock  %}

{% block content %}
<div
    class="d-flex flex-column flex-md-row gap-md-5 gap-3 align-items-start pt-5"
>
    <div class="d-flex flex-column w-md-50 gap-5">
        {% if request.user.is_authenticated %}
            <section style="background: #dadada" class="d-flex flex-column p-3 rounded-4">
                <div style="width: 50px; height: 50px" class="d-flex justify-content-center w-100 mb-3">
                    <img src="{{request.user.avatar.url}}" alt="avatar">
                </div>
                <p class="fw-bold">@{{request.user.username}} ({{request.user.name}})</p>
                <div class="fw-bold mb-3">
                    Created Blogs: {{request.user.blog_set.count}}
                </div>
                <a href="{% url "base:create-blog" %}" type="button" class="btn btn-success">Create New Blog</a>
            </section>
        {% endif %}

        {% if categoriesContent %}
            <section>
                <div class="list-group">
                    <a href="{% url "base:home" %}?category=all" class="list-group-item list-group-item-action {% if request.GET.category == 'all' or request.GET.category is None %}active{% endif %}">All</a>
                    {% for categoryName, count in categoriesContent.items %}
                    <a href="{% url "base:home" %}?category={{categoryName}}" class="list-group-item list-group-item-action {% if request.GET.category == categoryName %}active{% endif %}">{{categoryName}} <span class="badge text-bg-primary rounded-pill">{{count}}</span></a>
                    {% endfor %}
                </div>
            </section>
        {% endif %}
    </div>


    <section
        class="d-flex flex-column align-items-center justify-content-center w-100"
    >
        <div class="w-100">
            {% if blogs %}
                {% for blog in blogs %}
                    <div class="card mb-5">
                        <div class="card-body">
                            <a href="{% url 'base:blog-details' blog.id %}">
                                <h5 class="card-title">{{blog.title}} - @{{blog.author.username}}</h5>
                            </a>
                            <p class="card-text">
                                <div class="mb-3">
                                    
                                    {% for category in blog.category.all %}
                                        <span class="badge text-bg-secondary">{{category}}</span>
                                    {% endfor %}
                                </div>
                                <div class>
                                    {{blog.content}}
                                </div>
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <p class="card-text"><small class="text-body-secondary">created at <span class="text-black">{{blog.created_at}}</span></small></p>
                                {% if blog.author == request.user %}
                                    <div>
                                        <button id="{{blog.id}}" class="btn btn-danger delete-btn">Delete</button>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <img src="{{blog.image.url}}" class="card-img-bottom" alt="Blog Image" style="max-height: 400px;">
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </section>
</div>
{% endblock  %}

{% block script %}
    <script>
        document.querySelectorAll('.delete-btn').forEach(btn => {
            btn.addEventListener('click', async (e) => {
                const confirmed = window.confirm('Are you sure to delete this blog?')
                if (confirmed) {
                    const blogId = e.target.id;
                    const response = await fetch(`/blog/delete/${parseInt(blogId)}`, {
                        method: 'DELETE',
                        headers: {
                            'X-CSRFToken': '{{csrf_token}}'
                        }
                    });
                    e.target.parentElement.parentElement.parentElement.parentElement.remove();
                }
            });
        });
    </script>
{% endblock  %}

base/templates/base/sign-in.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
            crossorigin="anonymous"
        />
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
        <style>
            .gradient-custom {
                background: linear-gradient(90deg, #6912cb 0%, #2773fb 100%);
            }
        </style>
        <title>Sign In</title>
    </head>
    <body class="gradient-custom">
        <section class="vh-100 gradient-custom">
            <div class="container py-5 h-100">
                <div
                    class="row d-flex justify-content-center align-items-center h-100"
                >
                    <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                        <div
                            class="card bg-dark text-white"
                            style="border-radius: 1rem"
                        >
                            <div class="card-body p-5 text-center">
                                <div class="mb-md-5 mt-md-4 pb-5">
                                    <h2 class="fw-bold mb-2 text-uppercase">
                                        Login
                                    </h2>
                                    <p class="text-white-50 mb-5">
                                        Please enter your login and password!
                                    </p>
                                    <form action="" method="POST">
                                        {% csrf_token %}
                                        <div
                                            data-mdb-input-init
                                            class="form-floating mb-4"
                                        >
                                            <input
                                                type="email"
                                                name="email"
                                                id="email"
                                                placeholder="Email"
                                                class="form-control pt-4 pb-2"
                                            />
                                            <label
                                                for="email"
                                                class="form-label text-black"
                                                >Email</label
                                            >
                                        </div>
                                        <div
                                            data-mdb-input-init
                                            class="form-floating mb-4"
                                        >
                                            <input
                                                type="password"
                                                name="password"
                                                placeholder="Password"
                                                id="password"
                                                class="form-control pt-4 pb-2"
                                            />
                                            <label
                                                for="password"
                                                class="form-label text-black"
                                                >Password</label
                                            >
                                        </div>
                                        <button
                                            data-mdb-button-init
                                            data-mdb-ripple-init
                                            class="btn btn-outline-light btn-lg px-5"
                                            type="submit"
                                        >
                                            Login
                                        </button>
                                    </form>
                                </div>

                                <div>
                                    <p class="mb-0">
                                        Don't have an account?
                                        <a
                                            href={% url "base:sign-up" %}
                                            class="text-white-50 fw-bold"
                                            >Sign Up</a
                                        >
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>

        <script>
            function showToast(message) {
                Toastify({
                    text: message,
                    duration: 3000,
                    close: true,
                    gravity: "top",
                    position: "right",
                    stopOnFocus: true,
                    avatar: "{% static 'img/exclamation-mark.png' %}",
                    style: {
                        background: "#fff",
                        color: "red"
                    },
                    oldestFirst: false
                    }).showToast();
            }

            const error = "{{ error }}";
            if (error) showToast(error);
        </script>
    </body>
</html>